apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hello-app

resources:
  - namespace.yml
  - deployment.yml
  - service.yml
  - ingress.yml

images:
  - name: us-central1-docker.pkg.dev/long-door-483809/hello-repo/hello
    newTag: latest

